### PR TITLE
test adding a kind worker to test setup

### PR DESCRIPTION
**Pull request by vsoch**

### CODE REVIEW

**Comment by vsoch** [comment]
oh fluence, you are becoming very hard to maintain.

**Comment by vsoch** [comment]
okay I see the issue - the fluence job is pending, and likely it has to do with the testing environment (I can't reproduce this locally). 

```console
 NAME                                           READY   STATUS      RESTARTS   AGE
default-job-qljnp                              0/1     Completed   0          20s
fluence-84f444bcf6-x2t62                       2/2     Running     0          31s
fluence-job-2dkdr                              0/1     Pending     0          20s
scheduler-plugins-controller-dbdd9ff49-lmwqz   1/1     Running     0          31s
```
I'm going to do a describe pod to see _why_ it's pending and go from there.

**Comment by vsoch** [comment]
I think this is the issue:

IMG_6601

Likely its missing from the manifest, will look later.

**Review by cmisale — APPROVED** [review]

**Comment by vsoch** [comment]
Fixed by https://github.com/flux-framework/flux-k8s/pull/84

**Pull request closed without merging**
